"""
Argentina & the referees: a statistical look at penalty awards at the World Cup.

This script tests one specific, falsifiable question:
    Did Argentina receive penalties at a rate far above what the tournament
    baseline would predict, to a degree unlikely to be chance?

It deliberately ALSO reports the evidence that cuts the other way (cards drawn,
penalties conceded), because a one-sided analysis is not a credible one.

Run:  python src/analyze.py
Outputs: figures/*.png and reports/FINDINGS.md
"""

from pathlib import Path

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
FIG = ROOT / "figures"
REPORTS = ROOT / "reports"
FIG.mkdir(exist_ok=True)
REPORTS.mkdir(exist_ok=True)

# Argentina brand colors for charts
ARG_BLUE = "#75AADB"
ARG_NAVY = "#2B3A67"
ACCENT = "#D64545"


def load_baseline() -> dict:
    df = pd.read_csv(DATA / "tournament_baseline_2022.csv")
    return dict(zip(df["metric"], df["value"].astype(float)))


def poisson_test(observed: int, expected_rate_per_match: float, matches: int):
    """Under a null of the tournament-average penalty rate, how surprising is
    Argentina's haul? Model penalties in `matches` games as Poisson(lambda)."""
    lam = expected_rate_per_match * matches
    # P(X >= observed) under Poisson(lam)
    p_upper = stats.poisson.sf(observed - 1, lam)
    fold = observed / lam if lam else float("nan")
    return lam, fold, p_upper


def main():
    b = load_baseline()

    total_pens = b["total_penalties_awarded"]
    team_matches = b["team_matches"]
    arg_pens = b["argentina_penalties_for"]
    arg_matches = b["argentina_matches_played"]
    arg_conceded = b["argentina_penalties_against"]

    baseline_rate = total_pens / team_matches  # penalties per team-match
    lam, fold, p_val = poisson_test(int(arg_pens), baseline_rate, int(arg_matches))
    share = arg_pens / total_pens

    # Defensive side: were they "protected"? Compare conceded rate to baseline.
    arg_conceded_rate = arg_conceded / arg_matches

    lines = []
    lines.append("# Findings: Argentina & Referee Treatment (2022 World Cup)\n")
    lines.append("_Generated by `src/analyze.py`. Numbers trace to `data/` + `data/SOURCES.md`._\n")

    lines.append("## The headline stat\n")
    lines.append(
        f"- Argentina were awarded **{int(arg_pens)} of the {int(total_pens)} "
        f"open-play penalties** in the entire 2022 World Cup — "
        f"**{share*100:.1f}%** of every penalty in the tournament, to 1 of 32 teams.\n"
    )

    lines.append("## The formal test\n")
    lines.append(
        "Null hypothesis: Argentina drew penalties at the tournament-average rate, "
        "adjusted for how many games they played (they reached the final, so 7 games "
        "= more chances than a group-stage team). We model penalties per team-match as "
        "Poisson.\n"
    )
    lines.append(
        f"- Tournament baseline rate: **{baseline_rate:.3f} penalties per team-match** "
        f"({int(total_pens)} penalties / {int(team_matches)} team-matches).\n"
        f"- Expected penalties for a 7-game team at that rate: **{lam:.2f}**.\n"
        f"- Argentina actually got: **{int(arg_pens)}** — about **{fold:.1f}x** expectation.\n"
        f"- Poisson P(X >= {int(arg_pens)} | lambda = {lam:.2f}) = **{p_val:.4f}**.\n"
    )
    verdict = "statistically significant at alpha = 0.05" if p_val < 0.05 else "NOT significant at alpha = 0.05"
    lines.append(f"- **Verdict: {verdict}.**\n")

    lines.append("## The honest counterweight (do not omit this)\n")
    lines.append(
        f"- Argentina **conceded {int(arg_conceded)} penalties** in {int(arg_matches)} games "
        f"({arg_conceded_rate:.2f}/game vs a {baseline_rate:.2f}/game baseline) — both in the "
        "final. They were not shielded defensively.\n"
        f"- Argentina drew **{int(b['argentina_yellow_cards'])} yellow cards** in 7 games and "
        "played in the match with the most cards in World Cup history (18 vs Netherlands). "
        "A team that referees 'protect' does not lead the tournament in bookings.\n"
        "- **Confounder:** penalties are earned partly by play style. Argentina attacked, "
        "held the ball, and drew fouls in the box. Per-game normalization helps but cannot "
        "fully separate 'favoritism' from 'a lot of dangerous attacking touches.'\n"
    )

    lines.append("## What this does and does not prove\n")
    lines.append(
        "- It **does** show Argentina's penalty count was a genuine statistical outlier, "
        "not a vibe.\n"
        "- It **does not**, by itself, prove intent or bias — an outlier can be produced by "
        "style of play, deep tournament runs, and small samples. That distinction is the "
        "difference between a credible post and a conspiracy screenshot.\n"
    )

    (REPORTS / "FINDINGS.md").write_text("".join(lines))
    print("".join(lines))

    # ---- Figure 1: Argentina's share of all tournament penalties ----
    fig, ax = plt.subplots(figsize=(7, 4.2))
    others = total_pens - arg_pens
    ax.barh(["Rest of the field\n(31 teams)", "Argentina\n(1 team)"],
            [others, arg_pens], color=[ARG_NAVY, ACCENT])
    for i, v in enumerate([others, arg_pens]):
        ax.text(v + 0.2, i, f"{int(v)}", va="center", fontweight="bold")
    ax.set_xlabel("Open-play penalties awarded")
    ax.set_title(f"Argentina won {share*100:.0f}% of all penalties at the 2022 World Cup",
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig(FIG / "penalty_share.png", dpi=150)
    plt.close(fig)

    # ---- Figure 2: observed vs expected under the null ----
    fig, ax = plt.subplots(figsize=(7, 4.2))
    ax.bar(["Expected\n(tournament rate)", "Argentina\n(actual)"],
           [lam, arg_pens], color=[ARG_BLUE, ACCENT])
    ax.text(0, lam + 0.1, f"{lam:.1f}", ha="center", fontweight="bold")
    ax.text(1, arg_pens + 0.1, f"{int(arg_pens)}", ha="center", fontweight="bold")
    ax.set_ylabel("Penalties over 7 games")
    ax.set_title(f"~{fold:.1f}x more penalties than expected  (Poisson p = {p_val:.3f})",
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig(FIG / "observed_vs_expected.png", dpi=150)
    plt.close(fig)

    # ---- Figure 3: the counterweight ----
    fig, ax = plt.subplots(figsize=(7, 4.2))
    metrics = ["Penalties\nwon", "Penalties\nconceded", "Yellow cards\n(/7 games)"]
    vals = [arg_pens, arg_conceded, b["argentina_yellow_cards"]]
    ax.bar(metrics, vals, color=[ACCENT, ARG_NAVY, ARG_BLUE])
    for i, v in enumerate(vals):
        ax.text(i, v + 0.2, f"{int(v)}", ha="center", fontweight="bold")
    ax.set_title("The full picture: favored on penalties, but heavily carded",
                 fontweight="bold")
    fig.tight_layout()
    fig.savefig(FIG / "full_picture.png", dpi=150)
    plt.close(fig)

    print(f"\nWrote reports/FINDINGS.md and 3 figures to figures/.")


if __name__ == "__main__":
    main()
