"""
Three upgrades that move the project past a single penalty p-value:

  #1 EXPOSURE MODEL   -- Do Argentina get more penalties than their attacking
                         VOLUME predicts? Anchored on the cleanest possible control:
                         France, the other 2022 finalist (same 7 games), who took
                         MORE shots and generated EQUAL xG.
  #2 SCORECARD        -- The full refereeing picture across many metrics, so the
                         nuance (favored on penalties, punished on cards) is explicit.
  #3 PLACEBO CONTROL  -- Run the exact same outlier test on France. If the method
                         flags Argentina but NOT an equally-elite finalist, the signal
                         is Argentina-specific, not "any good team."

Run:  python src/exposure_and_scorecard.py
Outputs: figures/*.png and reports/EXPOSURE_FINDINGS.md
"""

from pathlib import Path

import pandas as pd
from scipy import stats
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
FIG = ROOT / "figures"
REPORTS = ROOT / "reports"

ACCENT = "#D64545"      # Argentina / pro-thesis
FRANCE = "#2B3A67"      # control
GOOD = "#3B7A57"        # favors argentina
BAD = "#9AA0A6"         # cuts against


def var_era_baseline() -> float:
    t = pd.read_csv(DATA / "tournament_penalty_totals.csv")
    v = t[t["var_era"] == "yes"]
    return v["total_penalties"].sum() / v["team_matches"].sum()


def main():
    rate = var_era_baseline()
    ex = pd.read_csv(DATA / "team_exposure_2022.csv").set_index("team")
    card = pd.read_csv(DATA / "argentina_scorecard_2022.csv")

    arg = ex.loc["Argentina"]
    fra = ex.loc["France"]

    def rates(row):
        return {
            "per_game": row.pens_for / row.games,
            "per_100_shots": 100 * row.pens_for / row.shots,
            "per_xg": row.pens_for / row.xg,
        }

    ra, rf = rates(arg), rates(fra)

    # Placebo: same Poisson test applied to France
    def pois(pens, games):
        lam = rate * games
        return lam, pens / lam, stats.poisson.sf(pens - 1, lam)
    la, folda, pa = pois(arg.pens_for, arg.games)
    lf, foldf, pf = pois(fra.pens_for, fra.games)

    L = []
    L.append("# Exposure, Scorecard & Placebo: Beyond the Penalty Count\n")
    L.append("_Generated by `src/exposure_and_scorecard.py`. Sources in `data/SOURCES.md`._\n")

    L.append("## #1 Exposure model — the 'they just attack more' rebuttal, tested\n")
    L.append(
        "The obvious objection to the penalty stat is: *Argentina attacked more, so of course "
        "they drew more penalties.* The cleanest test is the other finalist — **France played the "
        "same 7 games, took MORE shots, and generated essentially EQUAL xG.**\n"
    )
    L.append("| Metric | Argentina | France | Argentina / France |\n|---|---|---|---|\n")
    L.append(f"| Shots | {int(arg.shots)} | {int(fra.shots)} | {arg.shots/fra.shots:.2f}x |\n")
    L.append(f"| xG | {arg.xg} | {fra.xg} | {arg.xg/fra.xg:.2f}x |\n")
    L.append(f"| Penalties won | {int(arg.pens_for)} | {int(fra.pens_for)} | {arg.pens_for/fra.pens_for:.1f}x |\n")
    L.append(f"| Penalties per game | {ra['per_game']:.2f} | {rf['per_game']:.2f} | {ra['per_game']/rf['per_game']:.1f}x |\n")
    L.append(f"| **Penalties per 100 shots** | **{ra['per_100_shots']:.1f}** | **{rf['per_100_shots']:.1f}** | **{ra['per_100_shots']/rf['per_100_shots']:.1f}x** |\n")
    L.append(f"| Penalties per xG | {ra['per_xg']:.2f} | {rf['per_xg']:.2f} | {ra['per_xg']/rf['per_xg']:.1f}x |\n\n")
    L.append(
        f"**The rebuttal fails.** France attacked *more* (92 vs 76 shots) for *equal* xG, yet got "
        f"{arg.pens_for/fra.pens_for:.1f}x fewer penalties. On every exposure-adjusted basis — per "
        f"game, per shot, per xG — Argentina drew **{ra['per_100_shots']/rf['per_100_shots']:.1f}x-"
        f"{ra['per_game']/rf['per_game']:.1f}x** as many penalties as an equally elite side. "
        "The penalties are not a byproduct of raw attacking volume.\n"
    )
    L.append(
        "**Honest confounder:** Argentina's xG/shot was higher (0.155 vs 0.125) — their chances "
        "came from better positions, i.e. more time in dangerous areas. That plausibly earns *some* "
        "extra penalties. But a 15% edge in chance quality does not explain a 2.5-3x gap in penalty "
        "rate.\n"
    )

    L.append("## #2 The full refereeing scorecard — where the nuance lives\n")
    L.append("| Metric | Argentina | Field reference | Reading |\n|---|---|---|---|\n")
    for _, r in card.iterrows():
        tag = {1: "✅ favors Argentina", 0: "➖ neutral / confound", -1: "❌ cuts against"}[int(r.favors_argentina)]
        L.append(f"| {r.metric} | {r.argentina_value} | {r.field_reference} | {tag} |\n")
    L.append(
        "\n**The honest headline is narrow, and that is its strength:** Argentina were favored on "
        "**penalties specifically** — not on shots (France had more), and they were actively "
        "*punished* on discipline (16 yellows, the record 18-card match, 2 penalties conceded). "
        "'Referees hand Argentina everything' is false. 'Argentina drew penalties at a rate no "
        "attacking or historical baseline explains' is true.\n"
    )

    L.append("## #3 Placebo control — is the method just flagging good teams?\n")
    L.append(
        "If our outlier test lit up for any strong team, it would be worthless. So we run the "
        "identical Poisson test on France — an elite, high-shot, deep-run finalist:\n\n"
    )
    L.append("| Team | Penalties | Games | Expected | Fold | p-value | Flagged? |\n|---|---|---|---|---|---|---|\n")
    L.append(f"| Argentina | {int(arg.pens_for)} | {int(arg.games)} | {la:.2f} | {folda:.1f}x | {pa:.4f} | **YES** |\n")
    L.append(f"| France | {int(fra.pens_for)} | {int(fra.games)} | {lf:.2f} | {foldf:.1f}x | {pf:.3f} | no |\n\n")
    L.append(
        f"**The test discriminates.** Same games, same elite level: Argentina is flagged "
        f"(p = {pa:.3f}), France is not (p = {pf:.2f}). The anomaly is Argentina-specific, not an "
        "artifact of being a finalist. (And historically, no team *ever* got more than 4 penalties "
        "in an edition — so the placebo holds across all of World Cup history, not just France.)\n"
    )

    L.append("## Verdict\n")
    L.append(
        "- **The thesis survives its toughest test.** Argentina's penalties are not explained by "
        "attacking volume (France out-shot them for fewer), and the outlier test does not fire for "
        "a matched control.\n"
        "- **But it stays honest:** they were favored on penalties *only* — and punished on cards. "
        "And none of this proves *intent*. It proves an anomaly that the obvious innocent "
        "explanations do not account for. That is a real, defensible point — and the right ceiling "
        "for what data like this can claim.\n"
    )

    (REPORTS / "EXPOSURE_FINDINGS.md").write_text("".join(L))
    print("".join(L))

    # ---- Figure: exposure-adjusted rates, Argentina vs France ----
    fig, ax = plt.subplots(figsize=(8, 4.6))
    cats = ["Per game", "Per 100 shots", "Per xG"]
    avals = [ra["per_game"], ra["per_100_shots"], ra["per_xg"]]
    fvals = [rf["per_game"], rf["per_100_shots"], rf["per_xg"]]
    x = range(len(cats))
    ax.bar([i - 0.2 for i in x], avals, width=0.4, label="Argentina", color=ACCENT)
    ax.bar([i + 0.2 for i in x], fvals, width=0.4, label="France (more shots, equal xG)", color=FRANCE)
    for i, v in enumerate(avals):
        ax.text(i - 0.2, v + 0.05, f"{v:.2f}", ha="center", fontsize=9, fontweight="bold")
    for i, v in enumerate(fvals):
        ax.text(i + 0.2, v + 0.05, f"{v:.2f}", ha="center", fontsize=9)
    ax.set_xticks(list(x)); ax.set_xticklabels(cats)
    ax.set_ylabel("Penalties (exposure-adjusted)")
    ax.set_title("Exposure test: Argentina drew ~3x the penalties of an equally elite finalist",
                 fontweight="bold")
    ax.legend()
    fig.tight_layout(); fig.savefig(FIG / "exposure_arg_vs_france.png", dpi=150); plt.close(fig)

    # ---- Figure: scorecard favorable vs unfavorable ----
    fig, ax = plt.subplots(figsize=(8, 4.6))
    order = card.sort_values("favors_argentina", ascending=True)
    colors = [GOOD if v == 1 else (BAD if v == -1 else "#C9A227") for v in order.favors_argentina]
    ax.barh(order.metric, order.favors_argentina, color=colors)
    ax.set_xlim(-1.4, 1.4); ax.set_xticks([-1, 0, 1])
    ax.set_xticklabels(["Cuts against\nArgentina", "Neutral /\nconfound", "Favors\nArgentina"])
    ax.axvline(0, color="black", lw=0.8)
    ax.set_title("The full scorecard: favored on penalties, punished on cards, not tops on shots",
                 fontweight="bold")
    fig.tight_layout(); fig.savefig(FIG / "referee_scorecard.png", dpi=150); plt.close(fig)

    # ---- Figure: placebo ----
    fig, ax = plt.subplots(figsize=(7, 4.4))
    ax.bar(["Argentina", "France\n(placebo)"], [folda, foldf], color=[ACCENT, FRANCE])
    ax.axhline(1.0, color="black", lw=0.8, ls="--", label="baseline (1.0x)")
    ax.text(0, folda + 0.05, f"{folda:.1f}x\np={pa:.3f}", ha="center", fontweight="bold")
    ax.text(1, foldf + 0.05, f"{foldf:.1f}x\np={pf:.2f}", ha="center")
    ax.set_ylabel("Penalties vs baseline (fold)")
    ax.set_title("Placebo check: the test flags Argentina, not an equally elite finalist",
                 fontweight="bold")
    ax.legend()
    fig.tight_layout(); fig.savefig(FIG / "placebo_control.png", dpi=150); plt.close(fig)

    print("\nWrote reports/EXPOSURE_FINDINGS.md and 3 figures to figures/.")


if __name__ == "__main__":
    main()
